Simplify aggregation
We need to keep the "# type: ignore" because otherwise we get the
following error in mypy:

- conda_lock/src_parser/aggregation.py:42: error: Argument 1 to "merge"
  of "VersionedDependency" has incompatible type "VersionedDependency |
  URLDependency | VCSDependency | None"; expected "VersionedDependency |
  None"  [arg-type]
- conda_lock/src_parser/aggregation.py:42: error: Argument 1 to "merge"
  of "URLDependency" has incompatible type "VersionedDependency |
  URLDependency | VCSDependency | None"; expected "URLDependency | None"
  [arg-type]
- conda_lock/src_parser/aggregation.py:42: error: Argument 1 to "merge"
  of "VCSDependency" has incompatible type "VersionedDependency |
  URLDependency | VCSDependency | None"; expected "VCSDependency | None"
  [arg-type]